config/routes.rb
Rails.application.routes.draw do
  root 'news#index'
  resources :sources
  resources :news, only: [:index, :show]
  resource  :sessions, only: [:new, :create, :destroy]
  get 'sources/:id/refresh', to: 'sources#refresh',  as: 'refresh'
  get 'refresh_all',         to: 'news#refresh_all', as: 'refresh_all'
  get 'news/search',         to: 'news#search',      as: 'search'
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :source
  
  def self.update_from_feed(source)
    feed = Feedjira::Feed.fetch_and_parse(source.uri)
    add_entries(feed.entries, source.id)
  end
  
  def self.full_update
    Source.all.each do |source|
      feed = Feedjira::Feed.fetch_and_parse(source.uri)
      add_entries(feed.entries, source.id)
    end
  end
  
  def self.search(search)
    where("body LIKE ? or title LIKE ?", "%#{search}%", "%#{search}%")
  end
        
  private
  
  def self.add_entries(entries, source_id)
    entries.each do |entry|
      unless exists?(guid: entry.id)
        create!(
          title:     entry.title, 
          body:      entry.summary, 
          content:   entry.content,
          source_id: source_id,
          date:      entry.published,
          guid:      entry.id,
          url:       entry.url
        )
      end
    end
  end
  
  def self.by_date
    order('date desc')
  end
  
  def self.latest
    by_date.limit(1)
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
  validates :title,       presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :uri,         presence: true, length: { maximum: 255 }
  
  has_many :news, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @sources = Source.all
  end

  def show
    @news = News.find(params[:id])
  end

  def search
    @news = News.search(params[:search]).by_date.paginate(page: params[:page],
                                                          per_page: 10)
  end
  
  def refresh_all
    @news = News.all
    @news.full_update
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome aboard!"
    else
      flash.now[:alert] = "Combination Email/Password is invalid."
      render :new
    end
  end
  
  def destroy
    @current_user = nil
    session.delete(:user_id)
    redirect_to root_path, notice: "See you later!"
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :auth_user, except: [:show]
  before_action :get_source, only: [:show, :edit, :update, :destroy, :refresh]

  def index
    @sources = Source.all
  end
  
  def show
    @source_news = @source.news.by_date.paginate(page: params[:page],
                                                 per_page: 10)
  end
  
  def new
    @source = Source.new
  end
  
  def create
    @source = Source.new(source_params)
    if @source.save
      News.update_from_feed(@source)
      redirect_to @source, notice: "The source successfully added."
    else
      flash.now[:alert] = "The form contains some errors!"
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @source.update(source_params)
      redirect_to @source, notice: "The source successfully updated."
    else
      flash.now[:alert] = "The form contains some errors!"
      render :new
    end
  end
  
  def destroy
    @source.destroy
    redirect_to sources_path, notice: "Source deleted."
  end
  
  def refresh
    @source.news.update_from_feed(@source)
    redirect_to @source
  end
  
  private
  
  def source_params
    params.require(:source).permit(:title, :description, :uri)
  end
  
  def get_source
    @source = Source.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "News Portal"
    if page_title.empty?
      base_title
    else
      "#{page_title} · #{base_title}"
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    current_user != nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  private
  
  def auth_user
    redirect_to new_sessions_path, notice: "Please, log in." unless logged_in?
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">
    &copy; <%= Time.now.year %> <%= link_to "News Portal", "#" %>
  </div>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to "News portal", root_path, class: "logo" %></h1>
  <%= form_tag(search_path, method: :get, class: "search") do %>
    <%= text_field_tag :search, params[:search], placeholder: "search..." %>
    <%#= submit_tag "Search" %>
  <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<section class="sidebar">
  <nav>
    <% if logged_in? %>
    <p>Logged as <%= @current_user.email %></p>
    <% end %>
    <h2>Navigation</h2>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", "#" %></li>
      <% unless logged_in? %>
      <li><%= link_to "Sign in", new_sessions_path %></li>
      <% else %>
      <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
      <% end %>
    </ul>
    <h2>Sources</h2>
    <ul>
      <% Source.all.each do |source| %>
      <li><%= link_to source.title, source_path(source) %></li>
      <% end %>
    </ul>
    <% if logged_in? %>
    <h2>Admin</h2>
    <ul>
      <li><%= link_to "All sources",  sources_path %></li>
      <li><%= link_to "Add source",   new_source_path %></li>
      <li><%= link_to "Refresh news", refresh_all_path %></li>
    </ul>
    <% end %>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 
                                            'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <section class="content">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "flash flash-#{key}") %>
    <% end %>

    <%= yield %>
  </section>
  <%= render 'layouts/sidebar' %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/news/_entry.html.erb
<% @news.each do |entry| %>
  <article>
    <time pubdate datetime="<%= entry.date %>">
      <%= entry.date.to_formatted_s(:long) unless entry.date.nil?%>
    </time>
    <h3><%= link_to entry.title, entry %></h3>
    <p><%= sanitize entry.body %></p>
  </article>
<% end %>

app/views/news/index.html.erb
<h1>Last news</h1>

<% @sources.each do |source| %>
  <% @news = source.news.latest %>
  <h1><%= source.title %></h1>
  <%= render 'news/entry' %>
  <p><%= link_to "All news from #{source.title}", source %></p>
<% end %>

app/views/news/search.html.erb
<% provide(:title, "Search results") %>
<h1>Search results</h1>

<% if @news.present? %>

  <%= render 'news/entry' %>
  <%= will_paginate @news %>

<% else %>
  <p>There are no news containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/news/show.html.erb
<% provide(:title, "#{@news.title} / #{@news.source.title}") %>
<h1><%= link_to @news.title, @news.url %></h1>
<article>
  <time pubdate datetime="<%= @news.date %>">
    <%= @news.date.to_formatted_s(:long) unless @news.date.nil?%>
  </time>
  <%= sanitize(@news.content) || sanitize(@news.body) %>
</article>
<p><%= link_to "Back to #{@news.source.title}", @news.source %></p>

app/views/sources/_form.html.erb
<%= form_for @source, html: { class: "form" } do |f| %>

  <div id="errors">
    <% if @source.errors.any? %>
      The form contains <%= pluralize(@source.errors.count, "error") %>:
      <ul>
        <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :uri  %>
  <%= f.url_field :uri %>
  
  <%= f.submit %>

<% end %>

app/views/sources/edit.html.erb
<%= provide(:title, "#{@source.title} · Edit source") %>
<h1>Edit source</h1>

<%= render 'sources/form' %>

<p><%= link_to "Back to list", sources_path %></p>

app/views/sources/index.html.erb
<% provide(:title, "All sources") %>
<h1>All sources</h1>

<ul>
<% @sources.each do |source| %>
  <li>
    <%= link_to source.title, source %>
    [<%= link_to "refresh", refresh_path(source) %>]
    [<%= link_to "edit", edit_source_path(source) %>]
    [<%= link_to "del", source_path(source), method: :delete, 
                                      data: { confirm: "Are you sure?"} %>]
  </li>
<% end %>
</ul>

<%= link_to "Add new source", new_source_path %>

app/views/sources/new.html.erb
<%= provide(:title, "Add source") %>
<h1>Add source</h1>

<%= render 'sources/form' %>

<p><%= link_to "Back to list", sources_path %></p>

app/views/sources/show.html.erb
<% provide(:title, "#{@source.title}") %>
<h1><%= @source.title %></h1>

<% @source_news.each do |entry| %>
  <article>
    <time pubdate datetime="<%= entry.date %>">
      <%= entry.date.to_formatted_s(:long) unless entry.date.nil? %>
    </time>
    <h3><%= link_to entry.title, entry %></h3>
    <p><%= sanitize entry.body %></p>
  </article>
<% end %>
<%= will_paginate @source_news %>